# Generated by Django 5.2 on 2025-08-20 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_messages", "0002_messagereadstatus"),
    ]

    operations = [
        migrations.RenameField(
            model_name="group",
            old_name="name",
            new_name="groupname",
        ),
    ]
