# Generated by Django 5.2 on 2025-08-26 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_messages", "0003_rename_name_group_groupname"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="deleted",
            new_name="deleted_for_all",
        ),
        migrations.RenameField(
            model_name="messagereadstatus",
            old_name="is_deleted",
            new_name="is_hidden",
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="globally_deleted_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
