# Generated by Django 5.2 on 2025-08-29 09:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_messages", "0004_rename_deleted_message_deleted_for_all_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(
                fields=["user", "is_hidden"], name="user_messag_user_id_d0e660_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagereadstatus",
            index=models.Index(
                fields=["message", "user"], name="user_messag_message_ad5a9c_idx"
            ),
        ),
    ]
