project_name: nuagefernandez
project_root: "/opt/{{ project_name }}"
backend_src: "{{ (playbook_dir + '/../backend') | realpath }}"
frontend_src: "{{ (playbook_dir + '/../frontend') | realpath }}"
backend_dest: "{{ project_root }}/backend"
frontend_dest: "{{ project_root }}/frontend"
venv_dir: "{{ project_root }}/venv"
app_user: "nuage"
app_group: "nuage"
web_group: "www-data"
service_name: "nuage"
django_settings_module: "nuagefernandez.settings"
wsgi_module: "nuagefernandez.wsgi:application"
gunicorn_workers: 1
gunicorn_threads: 4
gunicorn_socket: "{{ project_root }}/gunicorn.sock"
frontend_build_cmd: "npm run build"