- name: Check current node version (if installed)
  command: node -v
  register: node_version
  ignore_errors: true
  changed_when: false

# Rôle Node.js
# On n'utilise PAS le paquet "nodejs" fourni par Debian, car :
# - il est souvent très en retard par rapport aux versions LTS/actuelles de Node.js
# - certaines fonctionnalités modernes (ES modules, librairies npm récentes) exigent une version plus récente
# - on veut garantir une version minimale (ici Node.js 22) identique en dev et en prod
# Solution : on purge nodejs/npm de Debian et on utilise le dépôt officiel NodeSource.
- set_fact:
    node_version_clean: "{{ node_version.stdout | regex_replace('^v', '') }}"
  when: node_version.rc == 0

- name: Remove Debian nodejs/npm
  apt:
    name: [nodejs, npm]
    state: absent
    purge: true
    autoremove: true
  when: node_version.rc != 0 or (node_version_clean is defined and node_version_clean is version('22.0.0', '<'))

- name: Download NodeSource 22 setup script
  get_url:
    url: https://deb.nodesource.com/setup_22.x
    dest: /tmp/nodesource_setup.sh
    mode: '0755'
  when: node_version.rc != 0 or (node_version_clean is defined and node_version_clean is version('22.0.0', '<'))

- name: Run NodeSource setup script
  command: /bin/bash /tmp/nodesource_setup.sh
  when: node_version.rc != 0 or (node_version_clean is defined and node_version_clean is version('22.0.0', '<'))

- name: Install Node.js 22
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Debug Node/NPM versions
  block:
    - command: node -v
      register: node_ver
      changed_when: false
    - debug:
        msg: "Node version: {{ node_ver.stdout }}"

    - command: npm -v
      register: npm_ver
      changed_when: false
    - debug:
        msg: "NPM version: {{ npm_ver.stdout }}"
